package cn.zhoujia.haowanapp.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import cn.zhoujia.haowanapp.greendao.Notepad;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "NOTEPAD".
*/
public class NotepadDao extends AbstractDao<Notepad, Long> {

    public static final String TABLENAME = "NOTEPAD";

    /**
     * Properties of entity Notepad.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Notepadcontent = new Property(1, String.class, "notepadcontent", false, "NOTEPADCONTENT");
        public final static Property Notepaddate = new Property(2, String.class, "notepaddate", false, "NOTEPADDATE");
    };


    public NotepadDao(DaoConfig config) {
        super(config);
    }
    
    public NotepadDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NOTEPAD\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NOTEPADCONTENT\" TEXT," + // 1: notepadcontent
                "\"NOTEPADDATE\" TEXT);"); // 2: notepaddate
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NOTEPAD\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Notepad entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String notepadcontent = entity.getNotepadcontent();
        if (notepadcontent != null) {
            stmt.bindString(2, notepadcontent);
        }
 
        String notepaddate = entity.getNotepaddate();
        if (notepaddate != null) {
            stmt.bindString(3, notepaddate);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Notepad readEntity(Cursor cursor, int offset) {
        Notepad entity = new Notepad( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // notepadcontent
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // notepaddate
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Notepad entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNotepadcontent(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setNotepaddate(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Notepad entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Notepad entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
